version: '3'

services:
  api:
    #env_file:
    #  "./api/api.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "localhost:5000/ibm-app-api"
    ports:
      - "6000:6000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    #network_mode: host
    #depends_on:
    #  - api
    image: "localhost:5000/ibm-app-client"
    ports:
      - "3000:3000"
    links:
      - "api"
